apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dariobaez.com
  dnsNames:
    - dariobaez.com
    - www.dariobaez.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dariobaez.com
          - www.dariobaez.com