apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - dariobaez.com
        - www.dariobaez.com
      secretName: dariobaez
  rules:
    - host: dariobaez.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-service
              servicePort: 8000
    - host: www.dariobaez.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-service
              servicePort: 8000